version: '3'

networks:
  shared-network:
    driver: bridge

services:
  db:
    image: postgres:12-alpine
    container_name: 'prime_db'
    networks:
      - shared-network
    restart: always
    ports: 
        - 5432:5432
    env_file: 
        - .env
    volumes:
        - data:/var/lib/postgresql/data

  # This sidecar allows for the viewing of traces.
  zipkin:
    container_name: zipkin
    networks:
      - shared-network
    image: openzipkin/zipkin:latest
    ports:
      - 9411:9411
    
volumes: 
  data:
